In [24]:
pip install -r requirements.txt

Requirement already satisfied: pandas in c:\Users\SMT07\llm_new\.venv\Lib\site-packages (from -r requirements.txt (line 1)) (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\SMT07\llm_new\.venv\Lib\site-packages (from pandas->-r requirements.txt (line 1)) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\SMT07\llm_new\.venv\Lib\site-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\SMT07\llm_new\.venv\Lib\site-packages (from pandas->-r requirements.txt (line 1)) (2026.1)
Requirement already satisfied: six>=1.5 in c:\Users\SMT07\llm_new\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 1)) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
import pandas as pd

In [27]:
inDf = pd.read_csv("./dataset/sample.txt")
inDf

  regionid   qty
0      a01   100

In [ ]:
# try - Exeception 기능 추가
try:
    inDf = pd.read_csv("./dataset/sample.txt")
    inDf
except exception as e :
    print(e)

In [35]:
inDf

  regionid   qty
0      a01   100

In [ ]:
# load .enc파일가져오기
# 이미지 파일 추가